<Class>
    <Id>344</Id>
    <Package>org.apache.derbyTesting.functionTests.tests.store</Package>
    <ClassName>RecoveryAfterBackup</ClassName>
    <SuperClass></SuperClass>
    <SuperInterfaceList>
        <SuperInterface></SuperInterface>
    </SuperInterfaceList>
    <ClassComment>RecoveryAfterBackup  /** 
 * This test contains a recovery for a database that did recovery just before it went down. After recovery more records are inserted into the database before the database is shutdown.  Then, roll-forward recovery of the database from the backup is performed.  It is then checked that the records inserted after the first recovery is still present.  This test was made to recreate the problem in DERBY-298. The test should be run after store/RecoveryAfterBackupSetup.java.
 * @see RecoveryAfterBackupSetup
 */
</ClassComment>
    <FieldList/>
    <MethodList>
        <Method>
            <MethodName>main</MethodName>
            <MethodComment></MethodComment>
            <ReturnType>void</ReturnType>
            <ParameterList>
                <Parameter>
                    <ParamName>argv</ParamName>
                    <ParamType>String[]</ParamType>
                </Parameter>
            </ParameterList>
            <InnerVarList>
                <InnerVar></InnerVar>
            </InnerVarList>
            <InnerMethodInvokeList>
                <InnerMethodInvoke></InnerMethodInvoke>
            </InnerMethodInvokeList>
            <ThrowExceptionList>
                <ExceptionType>Throwable</ExceptionType>
            </ThrowExceptionList>
        </Method>
    </MethodList>
</Class>