Some places in the code where SanityManager.THROWASSERT is used to wrap unexpected exceptions, the underlying exception is not linked to the assert exception. Therefore, the original stack trace, and possibly the message text, are lost. THROWASSERT(Throwable) or THROWASSERT(String,THROWABLE) should be used instead in these cases.
